Family_Hist_Project/config/routes.rb
Rails.application.routes.draw do
  resources :examples
  devise_for :users, :controllers => { registrations: 'registrations' }

  get 'welcome/index'

  get 'profiles/index'
  get 'profiles/edit'
  post 'profiles/create'
  patch 'profiles/update'
  get 'profiles/new'
  
  get '/videos/index'

  get 'dashboards/index'

  get 'pictures/index'
  get 'pictures/new' => 'pictures#new'
  post 'pictures/create'

  get 'memories/new' => 'memories#new'
  get 'memories/edit/:id' => 'memories#edit'
  get 'memories/index' => 'memories#index'
  get 'memories/:id' => 'memories#show', as: 'memory_show'
  post 'memories/create'

  resources :uploads

   root 'welcome#index'

end

Family_Hist_Project/app/views/partials/_layout_footer.html.erb
  <footer class="page-footer default-primary-color">
    <div class="container">
      <div class="row">
        <div class="col s8">
        <%= link_to root_path do%>
          <%= image_tag "MemoryTrunkLogoMenu.png", class:"footer-logo responsive-img" %>
        <% end %>
        </div>
        <div class="col s4">
          <ul>
            <li><a class="white-text" href="#!">Our Product</a></li>
            <li><a class="white-text" href="#!">About Us</a></li>
            <li><a class="white-text" href="#!">Contact</a></li>
            <li><a class="white-text" href="#!">Terms and Conditions</a></li>
          </ul>
        </div>
      </div>
    </div>
    <div class="footer-copyright dark-primary-color">
      <div class="container">© Copyright Memory Trunk - 2016</div>
    </div>
  </footer>

Family_Hist_Project/app/views/partials/_layout_header.html.erb
<nav class="default-primary-color" role="navigation">
  <div class="nav-wrapper container">
    
    <% if user_signed_in? %>
        <%= link_to root_path do%>
            <%= image_tag "MemoryTrunkIcon.png", class:"menu-logo brand-logo" %>
        <% end %>
    <% else %>
        <%= link_to root_path do%>
            <%= image_tag "MemoryTrunkIcon.png", class:"menu-logo brand-logo" %>
        <% end %>
    <% end %>
    
    <ul class="right hide-on-med-and-down">
      <% if user_signed_in? %>
        <li><%= link_to "Dashboard", dashboards_index_path%></li>
        <li><%= link_to "Memories", memories_index_path%></li>
        <li><%= link_to "My account", edit_user_registration_path, class:""%></li>
        <li><%= link_to "Log out", destroy_user_session_path, method: :delete, class:"" %></li>
      <% else %>
         <li><%= link_to "Log in", new_user_session_path, class:""%></li>
      <% end %>
    </ul>

    <ul id="nav-mobile" class="side-nav">
      <% if user_signed_in? %>
         <li><%= link_to "Dashboard", dashboards_index_path%></li>
         <li><%= link_to "Memories", memories_index_path%></li>
         <li><%= link_to "My account", edit_user_registration_path%></li>
         <li><%= link_to "Log out", destroy_user_session_path, method: :delete%></li>
      <% else %>
         <li><%= link_to "Log in", new_user_session_path%></li>
         <li><a href="#">About Us</a></li>
         <li><a href="#">Terms and Conditions</a></li>
      <% end %>
    </ul>
    <a href="#" data-activates="nav-mobile" class="button-collapse"><i class="material-icons">menu</i></a>
  </div>
</nav>

Family_Hist_Project/app/views/partials/_menu.html.erb
<%#  MENU PARTIAL %>

<%#<div class="row">
	<span>Welcome Back <%= current_user.name %>
<%#
<div class="row">
		<button href="#" data-dropdown="drop1" aria-controls="drop1" aria-expanded="false" class="button dropdown">Menu</button><br>
	<ul id="drop1" data-dropdown-content class="f-dropdown" aria-hidden="true">
		<li><a href="#">Videos</a></li>
		<li><a href="#">Personal Journal</a></li>
		<li><a href="#">Pictures</a></li>
	</ul>
</div>
%>
<br />
<div class="row">
	<div class="col s8 offset-s2 ">
		<nav class="breadcrumbs">
			<strong><%= link_to 'Dashboard', dashboards_index_path %></strong>
	  		<strong><%= link_to 'Profile', profiles_index_path %></strong>
	  		<strong><%= link_to 'Pictures', pictures_index_path %></strong>
	  		<strong><%= link_to 'Videos', videos_index_path %></strong>
	  		<strong><%= link_to 'Journal', examples_path %></strong>
		</nav>
	</div>
</div>

Family_Hist_Project/app/views/partials/_profile_form.erb
<div class="row">
	<%= f.label :date_of_birth %>
	<%=date_select "post", "create"%>
</div> 		
<div class="row">
	<%= f.label :city_born%>
	<%= f.text_field :city_born %>
</div> 
<div class="row">
	<%= f.label :hobbie %>
	<%= f.text_field :hobbie %>
</div> 
<div class="row">
	<%= f.label :dream %>
	<%= f.text_field :dream %>
</div> 
<div class="row">
	<%= f.label :job_history %>
	<%= f.text_field :job_history %>
</div> 
<div class="row">
	<%= f.label :fear %>
	<%= f.text_field :fear %>
</div> 
<div class="row">
	<%= f.label :biography %>
	<%= f.text_area :biography %>
</div>
<div class="row">
	<%= f.label :other %>
	<%= f.text_field :other %>
</div>