Family_Hist_Project/config/routes.rb
Rails.application.routes.draw do
  resources :examples
  devise_for :users, :controllers => { registrations: 'registrations' }

  get 'welcome/index'

  get 'profiles/index'
  get 'profiles/edit'
  post 'profiles/create'
  patch 'profiles/update'
  get 'profiles/new'
  
  get '/videos/index'

  get 'dashboards/index'

  get 'pictures/index'
  get 'pictures/new' => 'pictures#new'
  post 'pictures/create'

  get 'memories/new' => 'memories#new'
  get 'memories/edit/:id' => 'memories#edit'
  get 'memories/index' => 'memories#index'
  get 'memories/:id' => 'memories#show', as: 'memory_show'
  post 'memories/create'

  resources :uploads

   root 'welcome#index'

end

Family_Hist_Project/app/models/example.rb
class Example < ActiveRecord::Base
end

Family_Hist_Project/app/controllers/examples_controller.rb
class ExamplesController < ApplicationController
  before_action :set_example, only: [:show, :edit, :update, :destroy]

  # GET /examples
  # GET /examples.json
  def index
    @examples = Example.all
  end

  # GET /examples/1
  # GET /examples/1.json
  def show
  end

  # GET /examples/new
  def new
    @example = Example.new
  end

  # GET /examples/1/edit
  def edit
  end

  # POST /examples
  # POST /examples.json
  def create
    @example = Example.new(example_params)

    respond_to do |format|
      if @example.save
        format.html { redirect_to @example, notice: 'Example was successfully created.' }
        format.json { render :show, status: :created, location: @example }
      else
        format.html { render :new }
        format.json { render json: @example.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /examples/1
  # PATCH/PUT /examples/1.json
  def update
    respond_to do |format|
      if @example.update(example_params)
        format.html { redirect_to @example, notice: 'Example was successfully updated.' }
        format.json { render :show, status: :ok, location: @example }
      else
        format.html { render :edit }
        format.json { render json: @example.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /examples/1
  # DELETE /examples/1.json
  def destroy
    @example.destroy
    respond_to do |format|
      format.html { redirect_to examples_url, notice: 'Example was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_example
      @example = Example.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def example_params
      params.require(:example).permit(:title, :body, :comment, :Created_at)
    end
end

Family_Hist_Project/app/helpers/examples_helper.rb
module ExamplesHelper
end

Family_Hist_Project/app/views/examples/_form.html.erb
<%= form_for(@example) do |f| %>
  <% if @example.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@example.errors.count, "error") %> prohibited this example from being saved:</h2>

      <ul>
      <% @example.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :body %><br>
    <%= f.text_area :body %>
  </div>
  <div class="field">
    <%= f.label :comment %><br>
    <%= f.text_area :comment %>
  </div>
  <div class="field">
    <%= f.label :Created_at %><br>
    <%= f.date_select :Created_at %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

Family_Hist_Project/app/views/examples/edit.html.erb
<h1>Editing Example</h1>

<%= render 'form' %>

<%= link_to 'Show', @example %> |
<%= link_to 'Back', examples_path %>

Family_Hist_Project/app/views/examples/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Examples</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Body</th>
      <th>Comment</th>
      <th>Created at</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @examples.each do |example| %>
      <tr>
        <td><%= example.title %></td>
        <td><%= example.body %></td>
        <td><%= example.comment %></td>
        <td><%= example.Created_at %></td>
        <td><%= link_to 'Show', example %></td>
        <td><%= link_to 'Edit', edit_example_path(example) %></td>
        <td><%= link_to 'Destroy', example, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Example', new_example_path %>

Family_Hist_Project/app/views/examples/new.html.erb
<h1>New Example</h1>

<%= render 'form' %>

<%= link_to 'Back', examples_path %>

Family_Hist_Project/app/views/examples/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @example.title %>
</p>

<p>
  <strong>Body:</strong>
  <%= @example.body %>
</p>

<p>
  <strong>Comment:</strong>
  <%= @example.comment %>
</p>

<p>
  <strong>Created at:</strong>
  <%= @example.Created_at %>
</p>

<%= link_to 'Edit', edit_example_path(@example) %> |
<%= link_to 'Back', examples_path %>